# Generated by Django 4.2.5 on 2023-10-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
