# Generated by Django 4.2.5 on 2023-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
